import type { Player, Game, Tier } from "./manager";

export const defaultCsv = `student_number,     student_name,       waiver_signed,      team_name,      play_time,      comments,    signed_in
71716401,           Bobby Joe,          False,              C-rollers,      7:30,           mvp type shi,     false
73716401,           Another Joe,        True,               B-rollers,      7:30,           mvp type shi,     false
81816421,           Bobby Jane,         True,               C-rollers,      7:30,           mvp type shi,     false
72728401,           Sam Bigsam,         False,              Big-dawgs,      7:30,           mvp type shi,     false
`;

const mockPlayers: Player[] = [
  {
    student_number: "8181001",
    student_name: "Test Subject",
    waiver_signed: true,
    team_name: "Thunderbolts",
    team_tier: "A",
    team_id: "T001",
    signed_in: true,
  },
  {
    student_number: "7171001",
    student_name: "Alice Johnson",
    waiver_signed: true,
    team_name: "Thunderbolts",
    team_tier: "A",
    team_id: "T001",
    signed_in: true,
  },
  {
    student_number: "7171002",
    student_name: "Ben Thompson",
    waiver_signed: false,
    team_name: "Thunderbolts",
    team_tier: "A",
    team_id: "T001",
    signed_in: false,
  },
  {
    student_number: "7171003",
    student_name: "Catherine Li",
    waiver_signed: true,
    team_name: "Falcons",
    team_tier: "B",
    team_id: "T002",
    signed_in: true,
  },
  {
    student_number: "7171004",
    student_name: "David Kim",
    waiver_signed: true,
    team_name: "Falcons",
    team_tier: "B",
    team_id: "T002",
    signed_in: false,
  },
  {
    student_number: "7171005",
    student_name: "Emily Carter",
    waiver_signed: false,
    team_name: "Raptors",
    team_tier: "C",
    team_id: "T003",
    signed_in: false,
  },
  {
    student_number: "7171006",
    student_name: "Franklin Moore",
    waiver_signed: true,
    team_name: "Raptors",
    team_tier: "C",
    team_id: "T003",
    signed_in: true,
  },
  {
    student_number: "7171007",
    student_name: "Grace Nguyen",
    waiver_signed: true,
    team_name: "Lions",
    team_tier: "A",
    team_id: "T004",
    signed_in: true,
  },
  {
    student_number: "7171008",
    student_name: "Henry Patel",
    waiver_signed: false,
    team_name: "Lions",
    team_tier: "A",
    team_id: "T004",
    signed_in: false,
  },
  {
    student_number: "7171009",
    student_name: "Isabella Gomez",
    waiver_signed: true,
    team_name: "Cobras",
    team_tier: "B",
    team_id: "T005",
    signed_in: true,
  },
  {
    student_number: "7171010",
    student_name: "Jack Wilson",
    waiver_signed: true,
    team_name: "Cobras",
    team_tier: "B",
    team_id: "T005",
    signed_in: false,
  },
  {
    student_number: "7171011",
    student_name: "Katherine Brown",
    waiver_signed: false,
    team_name: "Wolves",
    team_tier: "C",
    team_id: "T006",
    signed_in: false,
  },
  {
    student_number: "7171012",
    student_name: "Liam Davis",
    waiver_signed: true,
    team_name: "Wolves",
    team_tier: "C",
    team_id: "T006",
    signed_in: true,
  },
  {
    student_number: "7171013",
    student_name: "Maria Rodriguez",
    waiver_signed: true,
    team_name: "Panthers",
    team_tier: "B",
    team_id: "T007",
    signed_in: false,
  },
  {
    student_number: "7171014",
    student_name: "Noah Anderson",
    waiver_signed: false,
    team_name: "Panthers",
    team_tier: "B",
    team_id: "T007",
    signed_in: true,
  },
  {
    student_number: "7171015",
    student_name: "Olivia Martinez",
    waiver_signed: true,
    team_name: "Eagles",
    team_tier: "A",
    team_id: "T008",
    signed_in: true,
  },
  {
    student_number: "7171016",
    student_name: "Paul Roberts",
    waiver_signed: false,
    team_name: "Eagles",
    team_tier: "A",
    team_id: "T008",
    signed_in: false,
  },
  {
    student_number: "7171017",
    student_name: "Quinn Stewart",
    waiver_signed: true,
    team_name: "Sharks",
    team_tier: "C",
    team_id: "T009",
    signed_in: false,
  },
  {
    student_number: "7171018",
    student_name: "Rachel Evans",
    waiver_signed: true,
    team_name: "Sharks",
    team_tier: "C",
    team_id: "T009",
    signed_in: true,
  },
  {
    student_number: "7171019",
    student_name: "Samuel Green",
    waiver_signed: false,
    team_name: "Bulls",
    team_tier: "B",
    team_id: "T010",
    signed_in: false,
  },
  {
    student_number: "7171020",
    student_name: "Tina Lewis",
    waiver_signed: true,
    team_name: "Bulls",
    team_tier: "B",
    team_id: "T010",
    signed_in: true,
  },
];

export const mockTeamA = {
  tier: "Mixed1" as Tier,
  name: "Crollers",
  players: mockPlayers.slice(0, 10),
};

export const mockTeamB = {
  tier: "Mixed1" as Tier,
  name: "Brollers",
  players: mockPlayers.slice(10, 20),
};

export const gameA: Game = {
  tier: "Mixed1",
  play_time: "7:30",
  field_name: "McInnes 1",
  home_team: mockTeamA,
  home_score: "incomplete",
  home_mvp: null,
  away_team: mockTeamB,
  away_score: "incomplete",
  away_mvp: null,
};

export const gameB: Game = {
  tier: "Mixed1",
  play_time: "8:30",
  field_name: "McInnes 2",
  home_team: mockTeamB,
  home_score: "incomplete",
  home_mvp: null,
  away_team: mockTeamA,
  away_score: "incomplete",
  away_mvp: null,
};
